
sudo: false

language: ruby

rvm:
  - 2.1.0

install:
  - bundle

before_script:
  - cp ./config/database.yml.travis ./config/database.yml
  - cp ./config/blacklight.yml.travis ./config/blacklight.yml
  - cp ./config/app_config.yml.travis ./config/app_config.yml
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:migrate:status RAILS_ENV=test
  - bundle exec rake locations:load RAILS_ENV=test
  # - RAILS_ENV=test bundle exec rake hours:sync
  - sh -c 'if [ -n "$QMAKE" ]; then sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa && sudo apt-get update && sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev; fi'

script: 
  - xvfb-run bundle exec rspec spec/features/catalog

env:
  global:
    - secure: E04d3CX7q2po3xtZmSmeOvNJ6zJyBX6R9C/dj729UvCf8SGxO3Gcd19Wh86NBRRm4ucnDBg1aq7vazjRDvOuFCdNqrB/I4caYUohSxLTgX2SmfSd74LebERii9FXsHwKrhvEh8me16kqsF+h9OoAcEvDn4e4f2ybiZfbSuqdUpc=
    - secure: XUMiorwZ3XGSf6ta/KHHHlq3lVQvkpESDiKD8lMyKsxJ96rTIjikstq8lTdJJ6W1c3dW8Di2Aq2Q/84TI2uuJWB8VcuyKfOaqKV31odDLSd+fOkl8Fthxvl7fUBCVBrAlsktANE/jdPSm77AgZrdIYGKNCi0EjWSyT8OhXEDCw4=
    - secure: Dr+TiUUDOOw8QDZeSLEu2HxKWF0yEfIMJCmnhhHTh6r+Tlt175QWHf80WSyPw/4ogUWRrFnnho+owPVw1aEDc8fpCZme0yj8G6qvWZPy1+hnkOWeZ5GGqBvjq6h+Jr5AE1IY3k6yQb7N07rN8M/n2PFw3LzC1pgpZwqmj4Xl2po=
    - secure: EfrKkxv6wbeU9Db9Bt4H5g/hACaHFVM7hs4bAi/4cpt4oOy6PEtjpZ4RPvrD6JW3jpLxHpLHXa0fk82dGO9b8RBhYhUwrBjBV0ZZOnxHSXvOdPvCId7Ljn98T9BHKAcOwHalGz1uBBoxC7tjc1/Wx3jSEg7S2B/Czlryx+E1Q3Q=
    - secure: FDNmfO1d/PpcH/WmkGd5Gnd+ejEDudewVnZnW5HLI3RYN2ZDgKvAvO7O+CmmK3aTAC9CvI104rFgjbYmnmV6mANSUfkYyZTEXWF/ky0EGScZmUlAySG5DuGUp2p+wmxlMf2Dw/edor1SY4OVittRhM4aPeuz4kvXpVS07vqGowU=
    - secure: AX2z9hDTJ54rm5IrhjIeIrRh/Z/A65QWQ04o6t69+1Oy0yOyzNm7eRZ+ww94mXpHJdBiOsOm03u7jwo7zaEg8IkezmVdyvdExxVOYeSv3dOgn7bsj9nISTRtcrZ7zVZSKCASq+uuclo4ZepNFDiEIgsubJ91YAwhwx5J0EQfIjk=
    - secure: hqMFUbVTVeWZgZxW48UGXQWqCS+/P/ocVA4avyGBCbx2OXKHNOx9HgGN2qtdxGAI8EHtpoVReqn9NJz+nCcJCnKDalwKQ0ke7KV/G8bGiYujBDa12jCqmj9vi52MOgi2bhZ38pDC6twiYASdJ2vosUmIN5RSPveMd0n810p3Ft8=
