###
### whatever it takes to get today's work done....
###

development:
  # url: http://machete.cul.columbia.edu:8983/solr-4.2.1/spectrum_prod
  # url: http://itak.cul.columbia.edu:8983/solr-4.2.1/spectrum_test
  # url: http://itak.cul.columbia.edu:8983/solr-4.2.1/spectrum_test
  # url: http://itak.cul.columbia.edu:8983/solr-4.2.1/spectrum_prod
  url: http://dirk.cul.columbia.edu:8983/solr-4.2.1/spectrum_prod_master
  # url: http://dirk.cul.columbia.edu:8983/solr-4.2.1/spectrum_test_master

test:
  # url: http://machete.cul.columbia.edu:8983/solr-4.2.1/spectrum_test
  # url: http://itak.cul.columbia.edu:8983/solr-4.2.1/spectrum_test
  url: http://machete.cul.columbia.edu:8983/solr-4.2.1/spectrum_prod
  # url: http://itak.cul.columbia.edu:8983/solr-4.2.1/spectrum_prod
  # url: http://dirk.cul.columbia.edu:8983/solr-4.2.1/spectrum_prod_master
  # url: http://dirk.cul.columbia.edu:8983/solr-4.2.1/spectrum_test_master
    


spectrum_test_master:
    url: http://dirk.cul.columbia.edu:8983/solr-4.2.1/spectrum_test_master

spectrum_prod_master:
    url: http://dirk.cul.columbia.edu:8983/solr-4.2.1/spectrum_prod_master


# authorities_prod_master:
#     url: http://machete.cul.columbia.edu:8983/solr-4.2.1/authorities_prod


# cloud1:
#   url: http://dirk.cul.columbia.edu:7501/solr/spectrum_prod
# 
# cloud2:
#   url: http://dirk.cul.columbia.edu:7502/solr/spectrum_prod
# 
# cloud3:
#   url: http://dirk.cul.columbia.edu:7503/solr/spectrum_prod
  
