datasources:
  quicksearch:
    name: Quicksearch
    no_facets: true
    search_box:
      route: quicksearch_index_path
      placeholder: Catalog, Articles, Academic Commons, Library Web 
  newspapers:
    name: Newspapers
    search_box:
      search_type: summon
      search_category: newspapers
      route: newspapers_index_path
      placeholder: Newspapers
  articles:
    name: Articles
    search_box:
      route: articles_index_path
      placeholder: Articles
      search_type: summon
      search_category: articles
  ebooks:
    name: E-Books
    no_facets: true
    search_box:
      route: ebooks_index_path
      placeholder: E-Books 
  dissertations:
    name: Dissertations
    no_facets: true
    search_box:
      route: dissertations_index_path
      placeholder: Dissertations
  catalog:
    name: Catalog
    search_box:
      route: base_catalog_index_path
      placeholder: Catalog
      search_type: blacklight
      advanced: true
      search_fields:
        all_fields: All Fields
        title: Title
        journal_title: Journal Title
        author: Author
        subject: Subject
        form_genre: Form\/Genre
        publication_place: Publiation Place
        publisher: Publisher
        publication_year: Publication Year
        isbn: 'ISBN'
        issn: ISSN
        call_number: Call Number
  archives:
    name: Archives
    search_box:
      advanced: true
      route: archives_index_path
      placeholder: Archives
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        author: Author
        subject: Subject
  databases:
    name: Databases
    search_box:
      advanced: true
      route: databases_index_path 
      placeholder: Databases
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        author: Author
        subject: Subject
  journals:
    name: E-Journal Titles
    search_box:
      advanced: true
      route: journals_index_path
      placeholder: E-Journal Titles
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        author: Author
        subject: Subject
  library_web:
    name: Library Web site
    no_facets: true
    search_box:
      route: library_web_index_path
      placeholder: Library Web
  academic_commons:
    name: Academic Commons
    search_box:
      route: academic_commons_index_path
      placeholder: Academic Commons
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        journal_title: Journal Title
        author: Author
        subject: Subject
  new_arrivals:
    name: New Arrivals
    search_box:
      route: new_arrivals_index_path
      placeholder: New Arrivals
      advanced: true
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        journal_title: Journal Title
        mauthor: Author
        subject: Subject
datasource_bar:
  major_sources:
    - quicksearch
    - catalog
    - articles
    - journals
    - databases
    - academic_commons
    - library_web
  minor_sources:
    - archives
    - dissertations
    - ebooks
    - new_arrivals
    - newspapers

