datasources:
  quicksearch:
    name: Quicksearch
    no_facets: true
    search_box:
      route: search_index_path
      placeholder: Catalog, Articles, Academic Commons, Library Web 
  newspapers:
    name: Newspapers
    no_facets: true
    search_box:
      route: newspapers_index_path
      placeholder: Newspapers
  articles:
    name: Articles
    search_box:
      route: articles_index_path
      placeholder: Articles
      search_type: summon
  ebooks:
    name: eBooks
    no_facets: true
    search_box:
      route: ebooks_index_path
      placeholder: eBooks 
  dissertations:
    name: Dissertations
    no_facets: true
    search_box:
      route: dissertations_index_path
      placeholder: Dissertations
  catalog:
    name: Catalog
    search_box:
      route: catalog_index_path
      placeholder: Catalog
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        journal_title: Journal Title
        author: Author
        subject: Subject
  archives:
    name: Archives
    search_box:
      route: archives_index_path
      placeholder: Archives
      search_type: blacklight
  databases:
    name: Databases
    search_box:
      route: databases_index_path 
      placeholder: Databases
      search_type: blacklight
  journals:
    name: Journal Titles
    search_box:
      route: journals_index_path
      placeholder: Journal Titles
      search_type: blacklight
  library_web:
    name: Library Web
    no_facets: true
    search_box:
      route: library_web_index_path
      placeholder: Library Web
  academic_commons:
    name: Academic Commons
    search_box:
      route: academic_commons_index_path
      placeholder: Academic Commons
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        journal_title: Journal Title
        author: Author
        subject: Subject
  new_arrivals:
    name: New Arrivals
    search_box:
      route: new_arrivals_index_path
      placeholder: New Arrivals
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        journal_title: Journal Title
        mauthor: Author
        subject: Subject
datasource_bar:
  major_sources:
    - quicksearch
    - catalog
    - articles
    - journals
    - databases
    - academic_commons
  minor_sources:
    - archives
    - dissertations
    - ebooks
    - new_arrivals
    - newspapers

