hilcc:
  1219: Arts, Architecture & Applied Arts 
  1044: Business & Economics
  1006: Engineering & Applied Sciences
  1299: General
  1028: Health Sciences
  1183: History & Archaeology
  1055: Journalism & Communications
  1186: Languages & Literatures
  1056: Law, Politics & Government
  1231: Music, Dance, Drama & Film
  1001: Philosophy & Religion
  1535: Sciences
  1089: Social Sciences


resource_types:
  ar: Archival Catalogs
  bc: E-Book Collections
  bi: Biographies
  ct: Library Catalogs
  di: Dictionaries
  dr: Directories
  ds: Dissertations
  en: Encyclopedias
  ft: Full-text Resources
  hb: Handbooks
  hi: Historical
  ia: Indexing & Abstracting Services
  im: Image Collections 
  ja: Articles (Journals)
  ma: Map & Atlas Collections 
  mi: Videos & Webcasts
  mu: Music Scores
  np: Newspaper Collections
  nu: Statistical Resources
  nw: Articles (Newspapers)
  sg: Subject Guides 
  sr: Sound Collections
  tc: Text Collections
  wb: Websites
