

'seymourdurst':
  txt: 'Seymour B. Durst Old York Library Collection, Avery Architectural & Fine Arts Library, Columbia University.'
  url: 'https://dlc.library.columbia.edu/durst'

'paullevitz':
  txt: ''
  url: ''

