--- 
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: African Studies
  :found_in: |-
    African Studies Reading Room
    607 Butler Library
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Ancient/Medieval
  :found_in: |-
    Ancient/Medieval Reading Room
    603 Butler Library
- :library_code: avery
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionE.gif
    Home Page: http://library.columbia.edu/indiv/avery.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionE.html
    Floorplans: http://library.columbia.edu/indiv/avery/floorplans.html
  :category: physical
  :location: Avery
  :found_in: |-
    Avery Architectural & Fine Arts Library
    
    Avery Hall
- :library_code: averydr
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionE.gif
    Home Page: http://library.columbia.edu/indiv/avery/da.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionE.html
    Floorplans: http://library.columbia.edu/indiv/avery/floorplans.html
  :category: physical
  :location: Avery Drawings
  :found_in: |-
    Avery Architectural & Fine Arts Library

    Avery Hall
- :library_code: averycl
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionE.gif
    Home Page: http://library.columbia.edu/indiv/avery/classics.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionE.html
    Floorplans: http://library.columbia.edu/indiv/avery/floorplans.html
  :category: physical
  :location: Avery Classics
  :found_in: |-
    Avery Architectural & Fine Arts Library

    Avery Hall
- :library_code: barnard
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionC.gif
    Home Page: http://library.barnard.edu/
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionC.html
    Floorplan: http://library.barnard.edu/using-library/floorplan
    Stacks Guide: http://library.barnard.edu/find-books/stacks
  :category: physical
  :location: Barnard
  :found_in: |-
    Barnard College Library
    
    Lehman Hall
- :links: 
    Home Page: http://bcrw.barnard.edu/
  :category: physical
  :location: Barnard Center For Research On Women
  :found_in: |-
    Barnard Center For Research On Women
    
    101 Barnard Hall
- :library_code: burke
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionA.gif
    Home Page: http://library.columbia.edu/indiv/burke.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionA.html
    Location Guide: http://library.columbia.edu/content/dam/libraryweb/floorplans/burke_location_guide.pdf
  :category: physical
  :location: Burke
  :found_in: |-
    Union Theological Seminary, Burke Library
    
    3041 Broadway @ 121st Street
- :library_code: business
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionD.gif
    Home Page: http://library.columbia.edu/indiv/business.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionD.html
    Floorplans: http://library.columbia.edu/content/dam/libraryweb/floorplans/business_floorplan.pdf
  :category: physical
  :location: Business
  :found_in: |-
    Business & Economics Library
    
    130 Uris
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/butler.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
    Call Number Guide: http://library.columbia.edu/content/dam/libraryweb/libraries/butler/butler_stacks.pdf
  :category: physical
  :location: Butler
  :found_in: |-
    Butler Library
    
    535 West 114th Street
- :library_code: bmc
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/bmc.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Butler Media
  :found_in: |-
    Butler Media Center
    
    208B Butler Library
- :library_code: pmrr
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/pmrr.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Butler Microforms
  :found_in: |-
    Butler Periodicals & Microforms Reading Room
    
    401 Butler Library
- :library_code: pmrr
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/pmrr.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Butler Periodicals
  :found_in: |-
    Butler Periodicals & Microforms Reading Room
    
    401 Butler Library
- :library_code: butlref
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Guides: http://library.columbia.edu/indiv/butlref.html
    Home Page: http://library.columbia.edu/indiv/butlref.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Butler Reference
  :found_in: |-
    Butler Reference
    
    301 Butler Library
- :library_code: butlres
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/butlres.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Butler Reserves
  :found_in: |-
    Butler Reserves
    
    208 Butler Library
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/butlcirc.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
    Call Number Guide: http://library.columbia.edu/content/dam/libraryweb/libraries/butler/butler_stacks.pdf
  :category: physical
  :location: Butler Stacks
  :found_in: |-
    Butler Circulation
    
    3rd Floor Butler Library
- :library_code: chemistryref
  :links: {}

  :category: physical
  :location: Chemistry Reference
  :found_in: "Ask at Mathematics and Science Library Circulation Desk\n\
    \xC2\xA0"
- :links: 
    Home Page: mailto:klg39@columbia.edu
  :category: no_location
  :location: Dakhla Library
  :found_in: |-
    Dakhla Oasis, Egypt.
    Not available on campus. Contact Karen Green klg39@columbia.edu with any questions.
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Early Modern/Modern Europe
  :found_in: |-
    Early Modern/Modern Europe Reading Room
    504 Butler Library
- :library_code: east asian
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionE.gif
    Home Page: http://library.columbia.edu/indiv/eastasian.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionE.html
  :category: physical
  :location: East Asian
  :found_in: |-
    Starr East Asian Library
    
    300 Kent Hall
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/dhc.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Electronic Text Service
  :found_in: |-
    Electronic Text Service
    
    305 Butler Library
- :library_code: eng
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionD.gif
    Home Page: http://library.columbia.edu/indiv/eng.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionD.html
  :category: physical
  :location: Engineering
  :found_in: |-
    Engineering Library
    
    422 Mudd
- :library_code: geology
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionD.gif
    Home Page: http://library.columbia.edu/indiv/geology.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionD.html
  :category: physical
  :location: Geology
  :found_in: |-
    Geology Library
    
    601 Schermerhorn
- :library_code: geosci
  :links: 
    Home Page: http://library.columbia.edu/indiv/geosci.html
  :category: physical
  :location: Geoscience
  :found_in: |-
    Geoscience Library, Lamont-Doherty
    
    Palisades, NY
- :library_code: hsl
  :links: 
    Home Page: http://library.cumc.columbia.edu/
    Floorplans: http://library.cumc.columbia.edu/library-floorplan
  :category: physical
  :location: Health Sciences
  :found_in: |-
    Health Sciences Library
    
    701 West 168th Street
- :links: {}

  :category: no_location
  :location: Health Sciences Web
  :found_in: |-
    Electronic Resource.
    Look for "Online Link" in record.
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Islamic Studies
  :found_in: |-
    Islamic Studies Reading Room
    602 Butler Library
- :library_code: jour
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/jour.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Journalism
  :found_in: |-
    Journalism Library
    
    203 Journalism
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Latin American Studies
  :found_in: |-
    Latin American Studies Reading Room
    503 Butler Library
- :library_code: lehman
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionF.gif
    Home Page: http://library.columbia.edu/indiv/lehman.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionF.html
    Floorplans: http://library.columbia.edu/indiv/lehman/floorplan.html
  :category: physical
  :location: Lehman
  :found_in: |-
    Lehman Social Sciences Library
    
    300 International Affairs
- :library_code: eds
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionF.gif
    Home Page: http://library.columbia.edu/indiv/dssc/data/service.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionF.html
  :category: physical
  :location: Lehman Electronic Data Service
  :found_in: |-
    Electronic Data Service
    
    215 International Affairs
- :library_code: lehman
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionF.gif
    Home Page: http://library.columbia.edu/indiv/maps.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionF.html
  :category: physical
  :location: Lehman Map Room
  :found_in: |-
    Lehman Map Room
    
    300 International Affairs
- :library_code: lehsuite
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionF.gif
    Home Page: http://library.columbia.edu/indiv/rbml/units/lehman.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionF.html
  :category: physical
  :location: Lehman Suite
  :found_in: |-
    Lehman Suite
    
    406 International Affairs
- :library_code: lehman
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionF.gif
    Home Page: http://library.columbia.edu/indiv/usgd.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionF.html
  :category: physical
  :location: Lehman US Government Documents
  :found_in: |-
    US Government Documents
    
    300 International Affairs
- :links: {}

  :category: no_location
  :location: LibraryWeb
  :found_in: |-
    Electronic Resource.
    Look for "Online Link" in record.
- :library_code: mathsci
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionE.gif
    Home Page: http://library.columbia.edu/indiv/math.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionE.html
  :category: physical
  :location: Math-Science
  :found_in: |-
    Mathematics/Science Library
    
    303 Mathematics
- :library_code: mathsci
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionE.gif
    Home Page: http://library.columbia.edu/indiv/math.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionE.html
  :category: physical
  :location: Mathematics
  :found_in: |-
    Mathematics/Science Library
    
    303 Mathematics
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/undergrad.html
    Shelving Guide: http://library.columbia.edu/indiv/undergrad/call_number_guide.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Milstein
  :found_in: |-
    Milstein Library (Undergraduate Library)
    
    Butler Library Rooms on the 2nd, 3rd & 4th floors
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Modern & Comparative Studies
  :found_in: |-
    Modern & Comparative Studies Reading Room
    504 Butler Library
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Moral & Political Theory
  :found_in: |-
    Moral & Political Theory Reading Room
    504 Butler Library
- :library_code: music
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionE.gif
    Home Page: http://library.columbia.edu/indiv/music.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionE.html
  :category: physical
  :location: Music
  :found_in: |-
    Music & Arts Library
    
    701 Dodge
- :links: 
    Home Page: http://nyspi.org/library/
  :category: physical
  :location: NYS Psychiatric Institute
  :found_in: |-
    NYS Psychiatric Institute Library
    
    1051 Riverside Drive at 168th StreetContact library for availability of items. Call (212) 543-5675.
- :links: 
    Home Page: http://library.columbia.edu/requestit/off-site.html
  :category: no_location
  :location: Offsite
  :found_in: |-
    Offsite Shelving Facility (ReCap)
    
    Use green "Get From Offsite" link in record to retrieve itemsNon-affiliates please contact LIO for access, lio@columbia.edu or (212) 854-7309
- :library_code: ohro
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/ccoh.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Oral History
  :found_in: |-
    Oral History Research Office
    
    801 Butler Library
- :links: 
    Home Page: http://www.nyp.org/columbiaortho/about/dep_rus.html?name1=Russell+Hibbs+Memorial+Library&type1=2Active
  :category: physical
  :location: Orthopaedic Surgery
  :found_in: |-
    Russell A. Hibbs Memorial Library
    
    622 W 168th Street - PH11-1139
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Papyrus & Epigraphy
  :found_in: |-
    Papyrus & Epigraphy
    604 Butler Library
- :library_code: rbml
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Home Page: http://library.columbia.edu/indiv/rbml.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: Rare Book
  :found_in: |-
    Rare Book & Manuscript Library
    
    6th Floor East, Butler Library
- :library_code: Science
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionE.gif
    Home Page: http://library.columbia.edu/indiv/math.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionE.html
  :category: physical
  :location: Science
  :found_in: |-
    Mathematics/Science Library
    
    303 Mathematics
- :library_code: socwk
  :links: 
    Home Page: http://library.columbia.edu/indiv/socwk.html
  :category: physical
  :location: Social Work
  :found_in: |-
    Social Work Library
    
    1255 Amsterdam Avenue @ 122nd Street
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: South Asian Studies
  :found_in: |-
    South Asian Studies Reading Room
    601 Butler Library
- :library_code: butler
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionG.gif
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionG.html
  :category: physical
  :location: US History & Literature
  :found_in: |-
    US History & Literature Reading Room
    502 Butler Library
- :library_code: uarchives
  :links: 
    Map URL: http://www.columbia.edu/cu/lweb/data/services/maps/images/sectionE.gif
    Home Page: http://library.columbia.edu/indiv/uarchives.html
    Map: http://www.columbia.edu/cu/lweb/services/maps/sectionE.html
  :category: physical
  :location: University Archives
  :found_in: |-
    Columbia University Archives
    
    6th Floor East, Butler Library
