site:
  manage:
    - jws2135
    - sam119
    - gb8

item_alerts:
  manage:
    - jws2135
    - aj204
    - am447
    - aom1
    - ar34
    - asb2154
    - at2186
    - bb145
    - bl23
    - jwb3
    - cak2158
    - mlc1
    - krc1
    - cmm2169
    - cmm64
    - jlc4
    - cs151
    - cw2165
    - ead1
    - dm2764
    - erg2104
    - fd2102
    - fh2238
    - pbg1
    - ecg2
    - kh33
    - avh1
    - hk368
    - hs2148
    - jc677
    - jc93
    - jf2156
    - jm86
    - jrs19
    - jt2118
    - jt628
    - jws2135
    - kd2145
    - kmk3
    - klg19
    - sk33
    - lh2112
    - ll162
    - pm2650
    - mc3395
    - mcb2212
    - mdk2126
    - mw18
    - mw2064
    - mz84
    - nef4
    - pm2650
    - pmg16
    - px2108
    - rd94
    - rf63
    - rhd2106
    - rkb7
    - rlb179
    - rhs1
    - sek26
    - sem2166
    - sn2160
    - shs4
    - jss8
    - sy2133
    - bas3
    - thc4
    - thomas
    - ur2
    - vjs4
    - jws824
    - raw7
    - yl105
    - bw12
    - cm119    



