versions:
  - version: "2.4.0"
    release_date: "Apr 25,2011"
    fixed:
      - Fixed issues with multiple titles.
      - Fixed issues with unicode searching, should work.
      - Fixed issue with grid view book jackets.
      - New production hardware, new ingest procedure.
  - version: "2.2.2"
    release_date: "Mar 1, 2011"
    fixed:
      - Changed publisher to full 260 field.
  - version: "2.2.1"
    release_date: "Feb 25,2011"
    fixed:
      - Included publisher information
      - Fixed phrase searching
  - version: "2.2.0"
    release_date: "Feb 24,2011"
    fixed:
      - Upgraded blacklight to 2.7
      - Reenabled functionality to search by author/title/subject
      - Added publication date facet
      - Added publication information
      - Changed way of determining format
      - Removed era facet 
  - version: "2.1.8"
    release_date: "Feb 18,2011"
    fixed:
      - Cleaned up ingest process to not take up so much space.
  - version: "2.1.7"
    release_date: "Feb 18, 2011"
    fixed:
      - Added more safeguards/logging for nightly update.
      - Added last three versions to homepage.
  - version: "2.1.6"
    release_date: "Feb 17, 2011"
    fixed: 
      - Added browser detection to feedback form.
      - Automatically ingest data feed every night.
      - Added front page list of current features
known_issues:
  - Availability information can be occasionally slow.
  - Selected items functionality does not work.
  - Clicking on an item in grid view does not let you return to search.
upcoming:
  - Better email/SMS formatting
  - Print functionality
