layouts:
  articles:
    style: articles
    columns:
      - searches:
          - source: articles 
            count: 10
  library_web:
    style: single
    columns:
      - searches:
          - source: library_web 
            count: 10
  quicksearch:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: catalog
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: articles
            count: 3
            row_opts:
              spans: [3,9] 
          - source: academic_commons
            count: 3
            row_opts:
              spans: [3,9]

          - source: library_web
            count: 3
            row_opts:
              spans: [3,9]
  newspapers:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: articles_newspapers
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: catalog_databases
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
  dissertations:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: catalog_dissertations
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: articles_dissertations
            count: 3
            row_opts:
              spans: [3,9] 
          - source: ac_dissertations 
            count: 3
            row_opts:
              spans: [3,9] 
  ebooks:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: catalog_ebooks 
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: ebooks 
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
sources:
  catalog:
    title: Catalog
    description: Contains library, books, videos, local resources
    holdings_check: true
    render_options:
      format: clio
  articles:
    title: Articles
    description: Contains articles, eBooks, electronic resources
    render_options:
      format: article
  academic_commons:
    title: Academic Commons
    description: Digital Repository of Research 
    render_options:
      format: ac
  library_web:
    title: Library Web
    description: Searches the library web site
    render_options:
      format: lweb
  ac_dissertations:
    title: Academic Commons
    description: Dissertations from Columbia's Digital Repository
    render_options:
      format: ac
  articles_dissertations:
    title: Summon
    description: Dissertations from Columbia's Articles Database
    render_options:
      format: articles
  articles_newspapers:
    title: Newspaper Articles
    description: Full text newspaper articles from Summon
    render_options:
      format: article
  catalog_databases:
    title: Databases
    description: Electronic resources
    render_options:
      format: clio
  catalog_dissertations:
    title: Catalog
    description: Dissertations, Thesises from Columbia's Catalog
    render_options:
      format: clio
  catalog_ebooks:
    title: Catalog
    description: eBooks from Catalog
    render_options:
      format: clio
  catalog_ejournals:
    title: Journal Titles
    description: Electronic Journals Held By Columbia
    render_options:
      format: ac
  ebooks:
    title: Summon
    description: eBooks from Summon's repository of digitzed books
    render_options:
      format: ebooks
    
    
    

