development:
    url: http://dirk.cul.columbia.edu:8080/solr-3.5/spectrum_test35
development_jetty:
    url: http://localhost:8983/solr
test: &TEST
    url: http://dirk.cul.columbia.edu:8080/solr-1.5/spectrum_test
na_dev:
    url: http://harding.cul.columbia.edu:8080/solr-1.5/na_experiment
na_test:
    url: http://harding.cul.columbia.edu:8080/solr-1.5/na_experiment
na_prod:
    url: http://harding.cul.columbia.edu:8080/solr-1.5/na_master
spectrum_dev:
    url: http://dirk.cul.columbia.edu:8080/solr-3.5/spectrum_test35
spectrum_test:
    url: http://dirk.cul.columbia.edu:8080/solr-3.5/spectrum_test35
spectrum_prod:
    url: http://dirk.cul.columbia.edu:8080/solr-3.5/spectrum_test35
cucumber:
    <<: *TEST


