production:
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/newbooks_prod
development:
    url: http://macana.cul.columbia.edu:8080/solr-1.5/newbooks
test: &TEST
    url: http://127.0.0.1:8983/solr
development_jetty:
    url: http://127.0.0.1:8983/solr
taft_dev:
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/newbooks_dev
taft_test:
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/newbooks_test
cucumber:
    <<: *TEST
rameau_prod:
    url: http://macana.cul.columbia.edu:8080/solr-1.5/newbooks

