development:
    url: http://dirk.cul.columbia.edu:8080/solr-1.5/spectrum_experiment
test: &TEST
    url: http://dirk.cul.columbia.edu:8080/solr-1.5/spectrum_test
na_dev:
    url: http://harding.cul.columbia.edu:8080/solr-1.5/na_experiment
na_test:
    url: http://harding.cul.columbia.edu:8080/solr-1.5/na_experiment
na_prod:
    url: http://harding.cul.columbia.edu:8080/solr-1.5/na_master
spectrum_dev:
    url: http://dirk.cul.columbia.edu:8080/solr-1.5/spectrum_experiment
spectrum_test:
    url: http://dirk.cul.columbia.edu:8080/solr-1.5/spectrum_experiment
cucumber:
    <<: *TEST


